In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("quikr_car (2).csv")

In [ ]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
df["Price"] = df["Price"].replace("Ask For Price", np.nan)
df["Price"] = df["Price"].str.replace(",", "", regex=False)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [ ]:
df = df.dropna(subset=["Price"])
df["Price"] = df["Price"].astype(int)

In [ ]:
df["Price"].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  275000,  285000,  340000,   70000,  289999,
        849999,  749999,  274999,  984999,  599999,  244999,  474999,
        245000,  169500,  370000,  168000,  145000,   98500,  209000,
        185000,  900000,  699999,  199999,  544999,  199000,  540000,
         49000,  700000,   55000,  895000,  355000,  565000,  365000,
         40000,  400000,  330000,  580000,  379000,  219000,  519000,
        730000, 2000000, 2100000, 1400000,  311000,  855000,  535000,
        178000,  300000,  255000,  549999,  380000,   57000,  410000,
        225000,  120000,   59000,  599000,  675000,   72500,  610000,
        230000,  520000,  524999,  424999,  644999,  584999,  799999,
        444999,  649999,  944999,  574999,  374999,  130000,  401000,
       1350000,  174999,  239999,   99999,  324999, 1074999, 1130000,
        149000,  770000,   30000,  335000,  399000,   65000,  169999,
        165000,  560000,  950000,  715000,   45000,  940000,  155555,
       1500000,  495000,  800000, 1299000,  530000, 1499000,   32000,
        405000,  760000,  750000,  419000,  140000, 1540000,  123000,
        498000,  480000,  488000, 1525000,  548900,  725000,   99000,
         52000, 2800000,  499000,  381000,  278000,  690000,  260000,
         90001,  115000, 1599000,  159000,   51999,  215000,   35000,
       1150000,  269000,   60000,  430000, 8500003,  401919,  490000,
        424000,  205000,  549900,  371500,  435000,  189700,  389700,
        360000,  295000,  114990, 1065000,  470000,   48000,  188000,
        465000,  179999, 2190000, 2390000, 1075000,  475000, 1025000,
        615000, 1900000, 1490000, 1510000, 1850000,  790000, 1725000,
       1225000,   68000,  970000, 3100000,  899000,   88000,   53000,
        568500,   71000,  590000,  795000,   42000,  189000,  162000,
         35999, 2900000,   39999,   50500,  510000,  860000,  500001])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 857 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        857 non-null    object
 1   company     857 non-null    object
 2   year        857 non-null    object
 3   Price       857 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.9+ KB

In [ ]:
df["kms_driven"] = (
    df["kms_driven"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("kms", "", case=False, regex=False)
    .str.strip()
)

df["kms_driven"] = pd.to_numeric(df["kms_driven"], errors="coerce")

In [ ]:
df = df.dropna(subset=["kms_driven"])

In [ ]:
df["kms_driven"] = df["kms_driven"].astype("Int64")

In [ ]:
df[df["kms_driven"].isin(["Petrol", "Diesel"])]

Empty DataFrame
Columns: [name, company, year, Price, kms_driven, fuel_type]
Index: []

In [ ]:
df['kms_driven'].unique()

<IntegerArray>
[ 45000,     40,  28000,  36000,  41000,  25000,  24530,  60000,  30000,
  32000,
 ...
   1625,  33400,  60123, 137495,  91200, 146000, 100800,   2100,   2500,
 132000]
Length: 247, dtype: Int64

In [ ]:
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["year"] = df["year"].astype("Int64")

In [ ]:
df["year"].unique()

<IntegerArray>
[2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018, 2011, 2019,
 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001]
Length: 21, dtype: Int64

In [ ]:
df["company"].unique()

array(['Hyundai', 'Mahindra', 'Ford', 'Maruti', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Land', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [ ]:
df["name"]=df["name"].str.split(" ").str.slice(0,3)

In [ ]:
df["name"]=df["name"].str.join(' ')

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df=df[df["Price"]<6e6].reset_index(drop=True)

In [ ]:
df.describe()

              year         Price    kms_driven
count        816.0  8.160000e+02         816.0
mean   2012.438725  4.016380e+05  46252.247549
std       4.004436  3.813805e+05  34304.743769
min         1995.0  3.000000e+04           0.0
25%         2010.0  1.750000e+05       27000.0
50%         2013.0  2.999990e+05       41000.0
75%         2015.0  4.900000e+05       56818.5
max         2019.0  3.100000e+06      400000.0

In [ ]:
df.to_csv('cleaned_car.csv')

In [ ]:
df.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

MODEL

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder

In [ ]:
x = df.drop("Price", axis=1)
y = df["Price"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
coln_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown="ignore"),
     ["name", "company", "fuel_type"]),
    remainder="passthrough"
)

In [ ]:
lr=LinearRegression()

In [ ]:
pipeline=make_pipeline(coln_trans,lr)

In [ ]:
pipeline.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = pipeline.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 120824.3302890901
RMSE: 189166.10886087312
R2 Score: 0.6667061889866989

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=0
)

rf_pipeline = make_pipeline(coln_trans, rf)

rf_pipeline.fit(x_train, y_train)

rf_pred = rf_pipeline.predict(x_test)

print("Random Forest MAE:",
      mean_absolute_error(y_test, rf_pred))

print("Random Forest RMSE:",
      np.sqrt(mean_squared_error(y_test, rf_pred)))

print("Random Forest R2:",
      r2_score(y_test, rf_pred))

Random Forest MAE: 92012.63269171023
Random Forest RMSE: 185122.94994384027
Random Forest R2: 0.6808013010126976